# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
   contentDir = "content/english"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
#[pt]
#  languageCode = "pt-bz"
#  contentDir = "content/portugues"
#  title = "Douglas Vinícius"
#  [pt.params]
#    description = "Site descrito em português-brasil..."
#  [[pt.menu.main]]
#    name = "Sobre"
#    url = "/about"
#    weight = 10
#
#  [[pt.menu.main]]
#    name = "Blog"
#    url = "/post"
#    weight = 20
#
#  [[pt.menu.main]]
#    name = "Palestras"
#    url = "/talks"
#    weight = 30
#
#  [[pt.menu.main]]
#    name = "Projetos"
#    url = "/projects"
#    weight = 40
#  
#  [[pt.menu.main]]
#    name = "CV"
#    url = "/resume"
#    weight = 50